name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Build documentation
        run: cargo doc --no-deps
      - name: Publish documentation
        run: |
          cd target/doc
          git init
          echo '<meta http-equiv="refresh" content="0; url=https://matter-labs.github.io/era_test_node/index.html">' > index.html
          git add .
          git -c user.name='ci' -c user.email='ci' commit -m 'Deploy documentation'
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages