name: publish

on:
  release:
    types: [published]

jobs:
  publish-to-crates:
    name: crates.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}
      
    - name: Update Cargo.toml version
      run: |
        chmod +x ./update_version.sh
        ./update_version.sh "${{ github.event.release.tag_name }}"
      
    - name: Publish to crates.io
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
