name: run

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: unit-tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly-2023-04-17

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install cargo-nextest
      run: cargo install cargo-nextest

    - name: Run tests
      run: cargo nextest run
