name: run

on:
  push:
    branches: [boojum-integration]
    tags:
      - 'v*'
  pull_request:
    branches: [boojum-integration]
  workflow_dispatch:
jobs:
  test:
    name: unit-tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Collect Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2023-07-20

    - name: Install cargo-nextest
      run: cargo install cargo-nextest

    - name: Run tests
      run: cargo nextest run
